### ISSUE TITLE
code什么时候公开？

### ISSUE THREAD

**Issue by Gj-12222** [zhou-huafei/CEBRNet#1]
空项目有啥意思？

**Comment by zhou-huafei** [comment]
> 空项目有啥意思？

你好  因工作繁忙原因 代码稍晚公布。如有兴趣或疑问，欢迎邮件联系，谢谢！

**Comment by mingasx** [comment]
> > 空项目有啥意思？
> 
> 你好 因工作繁忙原因 代码稍晚公布。如有兴趣或疑问，欢迎邮件联系，谢谢！

你好，啥时候公开代码，你的邮箱能听提供下吗，IEEE那个发送失败

**Comment by zhou-huafei** [comment]
16085174@qq.com@mingasx

**Comment by zhou-huafei** [comment]
16085174@qq.com @mingasx
